
-- Get the quiz topic ID for network services (create if it doesn't exist)
INSERT INTO quiz_topics (name, description, color) 
VALUES ('Supporting Network Services', 'Server roles, AAA services, network appliances, and virtual networks', 'purple')
ON CONFLICT (name) DO NOTHING;

-- Insert Week 6 practice questions
WITH network_services_topic AS (
  SELECT id FROM quiz_topics WHERE name = 'Supporting Network Services'
)

INSERT INTO practice_questions (topic_id, question, options, correct_answer, explanation, difficulty, week_number) VALUES

-- Server Roles and Network Services
((SELECT id FROM network_services_topic),
 'What is the primary function of a print server in a network environment?',
 '["Store user documents", "Manage and share printers across the network", "Provide internet connectivity", "Handle email distribution"]'::jsonb,
 1,
 'Print servers centralize printer management, allowing multiple users to access shared printers and manage print queues efficiently.',
 'Easy',
 6),

((SELECT id FROM network_services_topic),
 'Which server role is responsible for collecting and storing log messages from various network devices?',
 '["File server", "Web server", "Syslog server", "Mail server"]'::jsonb,
 2,
 'Syslog servers centralize log collection from network devices, routers, switches, and servers for monitoring and troubleshooting purposes.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What type of server would be used to host internal company websites and applications?',
 '["Print server", "Web server", "Authentication server", "Backup server"]'::jsonb,
 1,
 'Web servers host websites, web applications, and intranet sites, serving content to users via HTTP/HTTPS protocols.',
 'Easy',
 6),

((SELECT id FROM network_services_topic),
 'Which server component verifies user credentials before granting network access?',
 '["File server", "Print server", "Authentication server", "Proxy server"]'::jsonb,
 2,
 'Authentication servers verify user credentials (usernames/passwords) before allowing access to network resources and services.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What is the main purpose of a file server in an enterprise network?',
 '["Route network traffic", "Provide centralized file storage and sharing", "Manage IP addresses", "Handle wireless connections"]'::jsonb,
 1,
 'File servers provide centralized storage where users can save, access, and share files across the network with proper permissions.',
 'Easy',
 6),

-- Authentication, Authorization, and Accounting (AAA)
((SELECT id FROM network_services_topic),
 'In AAA services, what happens during the Authorization phase?',
 '["User identity is verified", "User activities are logged", "Access permissions are determined", "Passwords are encrypted"]'::jsonb,
 2,
 'Authorization determines what resources, files, or services a user can access after successful authentication.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What information is typically collected during the Accounting phase of AAA?',
 '["User passwords", "Network topology", "User activity logs and resource usage", "Hardware specifications"]'::jsonb,
 2,
 'Accounting tracks and logs user activities, session duration, and resource usage for auditing and billing purposes.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'Which type of server commonly provides centralized AAA services?',
 '["File server", "RADIUS server", "Web server", "Print server"]'::jsonb,
 1,
 'RADIUS (Remote Authentication Dial-In User Service) servers provide centralized AAA services for network access control.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What happens if authentication fails in an AAA system?',
 '["User gets limited access", "User is granted full access", "User access is denied", "System shuts down"]'::jsonb,
 2,
 'If authentication fails, the user cannot prove their identity and is denied access to network resources.',
 'Easy',
 6),

((SELECT id FROM network_services_topic),
 'Which AAA component would track how long a user was connected to the network?',
 '["Authentication", "Authorization", "Accounting", "Access control"]'::jsonb,
 2,
 'Accounting tracks session information including connection duration, data transferred, and resources used.',
 'Medium',
 6),

-- Internet Appliances
((SELECT id FROM network_services_topic),
 'What is the primary function of a spam gateway appliance?',
 '["Route internet traffic", "Filter and block unwanted email messages", "Provide wireless access", "Manage user passwords"]'::jsonb,
 1,
 'Spam gateways analyze incoming and outgoing email to filter spam, malware, and other unwanted messages before they reach users.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'Which appliance combines firewall, antivirus, and intrusion detection in one device?',
 '["Simple router", "Basic switch", "UTM (Unified Threat Management) device", "Standard modem"]'::jsonb,
 2,
 'UTM appliances integrate multiple security functions including firewall, antivirus, intrusion detection, and content filtering.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What does a load balancer accomplish in a network?',
 '["Balances electrical power usage", "Distributes incoming requests across multiple servers", "Balances network cable lengths", "Manages user account loads"]'::jsonb,
 1,
 'Load balancers distribute incoming network traffic across multiple servers to prevent overload and ensure high availability.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'Which appliance acts as an intermediary between clients and destination servers?',
 '["Load balancer", "Spam gateway", "Proxy server", "UTM device"]'::jsonb,
 2,
 'Proxy servers act as intermediaries, often providing caching, content filtering, and security services between clients and servers.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What benefit does a proxy server provide for web browsing?',
 '["Increases internet speed for everyone", "Caching frequently accessed content for faster access", "Eliminates the need for web browsers", "Automatically fixes broken websites"]'::jsonb,
 1,
 'Proxy servers cache frequently requested web content, reducing bandwidth usage and improving response times for users.',
 'Medium',
 6),

-- Legacy/Embedded Systems
((SELECT id FROM network_services_topic),
 'What type of environment typically uses SCADA systems?',
 '["Home offices", "Small retail stores", "Industrial control and manufacturing facilities", "Mobile device networks"]'::jsonb,
 2,
 'SCADA systems monitor and control industrial processes in power plants, water treatment facilities, manufacturing, and infrastructure.',
 'Hard',
 6),

((SELECT id FROM network_services_topic),
 'What is a major security concern with legacy embedded systems?',
 '["They use too much bandwidth", "They cannot be powered off", "They often lack security updates and patches", "They require constant user interaction"]'::jsonb,
 2,
 'Legacy embedded systems frequently cannot receive security updates, making them vulnerable and requiring network isolation.',
 'Hard',
 6),

((SELECT id FROM network_services_topic),
 'Which of the following is an example of an IoT device?',
 '["Desktop computer", "Smart door lock", "Traditional landline phone", "Standard keyboard"]'::jsonb,
 1,
 'Smart door locks are IoT devices that connect to networks to provide remote access control and monitoring capabilities.',
 'Easy',
 6),

((SELECT id FROM network_services_topic),
 'What security measure is recommended for IoT devices on enterprise networks?',
 '["Give them full network access", "Segment them on a separate VLAN", "Connect them directly to the internet", "Disable all network security"]'::jsonb,
 1,
 'IoT devices should be segmented on separate VLANs to limit their network access and contain potential security breaches.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What challenge do embedded systems present for network administrators?',
 '["They consume too much power", "They are too fast for networks", "They often have limited configuration options and interfaces", "They require constant software updates"]'::jsonb,
 2,
 'Embedded systems typically have minimal interfaces and configuration options, making security and management challenging.',
 'Medium',
 6),

-- Network Troubleshooting Symptoms
((SELECT id FROM network_services_topic),
 'What does "intermittent wireless connectivity" typically indicate?',
 '["Perfect wireless operation", "Signal interference or weak signal strength", "Too much security on the network", "Excessive internet bandwidth"]'::jsonb,
 1,
 'Intermittent wireless connectivity usually results from interference, distance from access point, or physical obstacles.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What network issue is indicated by slow file transfers but normal web browsing?',
 '["DNS problems", "Local network congestion or server issues", "Internet connectivity failure", "Wireless interference"]'::jsonb,
 1,
 'Slow file transfers with normal web browsing suggests issues with local network infrastructure or file server performance.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What does "limited connectivity" typically mean in network troubleshooting?',
 '["Full internet access", "Can access local network but not the internet", "No network access at all", "Only wireless access available"]'::jsonb,
 1,
 'Limited connectivity usually means local network communication works but internet access is blocked, often due to gateway issues.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What can cause high network latency?',
 '["Too much available bandwidth", "Network congestion or routing issues", "Perfect network configuration", "Fast network hardware"]'::jsonb,
 1,
 'High latency results from network congestion, inefficient routing, or long physical distances between network nodes.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What network problem affects VoIP call quality the most?',
 '["High bandwidth", "Jitter and packet loss", "Low network utilization", "Fast switching"]'::jsonb,
 1,
 'Jitter (variable packet delays) and packet loss significantly degrade VoIP call quality, causing choppy or dropped audio.',
 'Hard',
 6),

-- Virtual Networks
((SELECT id FROM network_services_topic),
 'What is the primary benefit of implementing VLANs?',
 '["Increases physical network speed", "Logically segments network traffic for security", "Eliminates the need for switches", "Reduces cable costs"]'::jsonb,
 1,
 'VLANs provide logical network segmentation without requiring separate physical networks, improving security and organization.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'How do VLANs improve network security?',
 '["By encrypting all data", "By isolating different groups of users and devices", "By blocking all network traffic", "By removing all passwords"]'::jsonb,
 1,
 'VLANs isolate traffic between different user groups, preventing unauthorized access to sensitive network segments.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What is required for devices on different VLANs to communicate?',
 '["Same physical switch", "Router or Layer 3 switch", "Same IP address range", "Direct cable connection"]'::jsonb,
 1,
 'Inter-VLAN communication requires a router or Layer 3 switch to route traffic between different VLAN segments.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What protocol is commonly used to create secure VPN tunnels?',
 '["HTTP", "FTP", "IPSec", "TELNET"]'::jsonb,
 2,
 'IPSec (Internet Protocol Security) provides encryption and authentication for secure VPN tunnel creation.',
 'Medium',
 6),

((SELECT id FROM network_services_topic),
 'What is the main advantage of using a VPN for remote workers?',
 '["Faster internet speeds", "Secure access to company network resources", "Eliminates the need for passwords", "Provides free internet access"]'::jsonb,
 1,
 'VPNs create encrypted tunnels allowing remote workers to securely access company network resources over the internet.',
 'Medium',
 6);
