// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yadunyampsjjukwnpsay.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlhZHVueWFtcHNqanVrd25wc2F5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NjE0MDQsImV4cCI6MjA2MDQzNzQwNH0.VP6XxrnRvj8arcgo6u9ZmzrwM1dZN6kVCN5Egb9y3Ls";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);